name: dartml
description: A simple machine learning library in Dart
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
# Add any dependencies here

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
